version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Python 환경 준비 중..."
      - python --version
      - pip --version

  pre_build:
    commands:
      - echo "의존성 설치 중..."
      - pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  build:
    commands:
      - echo "NAVER CAMPING AI 빌드 시작"
      - echo "빌드 완료!"

  post_build:
    commands:
      - echo "빌드 후 정리 작업"
      - ls -la

artifacts:
  files:
    - '**/*'
  name: camping-ai-build-$(date +%Y%m%d-%H%M%S).zip
